name: flutter_github_search
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cached_network_image:
  cupertino_icons:
  dio:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  freezed:
  freezed_annotation:
  gap:
  hooks_riverpod: 2.0.0-dev.5
  intl:
  json_annotation:
  package_info_plus:
  shared_preferences:
  state_notifier:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
